use_frameworks!

target 'PaymentGatewaysShivaKit_Example' do
  pod 'PaymentGatewaysShivaKit', :path => '~/PaymentGatewaysShivaKit'

  target 'PaymentGatewaysShivaKit_Tests' do
    inherit! :search_paths

    
  end
  
  pod 'OpenSSL'
  
  pod 'TFHpple'
end
